### ISSUE TITLE
Selecionar posição da sprite na spritesheet

### ISSUE THREAD

**Issue by ratatusznei** [ratatusznei/time-travel#17]
Implementar um jeito de fazer isso

**Comment by alveSokulski** [comment]
fazer uma "coleção" de todas as texturas possíveis de cada entidadedinamica
quando a primeira entidadedinamica de um determinado tipo é instanciada, ele carrega a coleção daquele tipo, que só é carregada uma vez
de quebra já consegue um flyweight
só o que vai mudar é o intrect de cada entidadedinamica

**Comment by alveSokulski** [comment]
serve também pra entidadeestatica

**Comment by alveSokulski** [comment]
eu acho
